import type { Metadata } from "next";
import "./globals.css";
import ClerkProviderWrapper from "./components/ClerkProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProviderWrapper>
      <html lang="en" data-theme="retro">
        <body className="antialiased">
          {children}
        </body>
      </html>
    </ClerkProviderWrapper>
  );
}
